### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Tracker997** [Chris230291/STB-Proxy#16]
My problem:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/STBpNew/app.py", line 214, in editorSave
    portals[portal]["enabled channels"].append(channelId)
KeyError: None

i'm click the save button to channel list and not work :\

**Comment by Tracker997** [comment]
My portal: 
http://live.hutv.me:25461/c/

**Comment by Tracker997** [comment]
Hello
My new server not work...
Please help!

http://live.huntv.net:8080/c
00:1A:79:0C:B1:54
