### ISSUE TITLE
 Flask crash when saving ! [BUG] [CRITICAL]

### ISSUE THREAD

**Issue by CyberPoison** [Chris230291/STB-Proxy#23]
![image](https://user-images.githubusercontent.com/60718477/155767803-7a547c90-dde2-4d7f-b5bf-7366f66292ba.png)

I assume there is a issue with some naming on the channels. when parsed to the paylist.

here is the logs.
```
- [25/Feb/2022 18:23:01] "POST /editor/save HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/app.py", line 261, in editorSave
    portals[portal]["enabled channels"].append(channelId)
KeyError: None
```

i can share with you some access to the stb portal so you can test. 

Installation method Docker.

**Comment by Chris230291** [comment]
Sure you can share the info if you like. Let me know which channels/names cause the problem and I will see if I can figure it out.

**Comment by CyberPoison** [comment]
> Sure you can share the info if you like. Let me know which channels/names cause the problem and I will see if I can figure it out.

Hi again, my friend after some checks i think the issue is from the all check mark.

When you trigger to enable all the streams. Btw do you have a telegram so i can send you a message with portal url and mac address so you can heavily test you app.

Kind regards

**Comment by Chris230291** [comment]
I was able to fix the enable all checkbox. There was an obvious error in the html and a weird issue I don't understand (but was able to change) in the python.
