### ISSUE TITLE
Error for playing some channels

### ISSUE THREAD

**Issue by rockydares** [Chris230291/STB-Proxy#28]
`UnboundLocalError
UnboundLocalError: local variable 'cmd' referenced before assignment

Traceback (most recent call last)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/root/STB-Proxy/app.py", line 535, in channel
if "http://localhost/" in cmd:
UnboundLocalError: local variable 'cmd' referenced before assignment`

Facing this problem for few channels while all others are streaming well.

**Comment by Chris230291** [comment]
Maybe because the channel is missing or changed ID.
I am part way through making lots of changes and errors like this are logged much better.

**Comment by Chris230291** [comment]
If you still have issues after I update, then we can look into it better.

**Comment by rockydares** [comment]
Sure, btw this app is already sufficient (with latest addition) and serves the purpose.

**Comment by Chris230291** [comment]
Ye it has been great for me.
The only issue I have is that I have to run multiple instances of it.
I fix that in the next version with the ability to add multiple macs per portal.
