### ISSUE TITLE
[Feature Request OR Bug maybe?] Allow multiples occupations on mac.

### ISSUE THREAD

**Issue by CyberPoison** [Chris230291/STB-Proxy#37]
Hello, in your previous code it was possible to add multiple occupations using same Mac could you, manage adding a way to allow multiple occupations again please, designed by parameters (5,10,20,unlimited) ? 
And a way to terminate directly a stream/occupation also will be nice.

**Comment by CyberPoison** [comment]
This is the error i get when trying to reopen a other Channel with the same MAC.
```BASH
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/cyberpoison/Projects/Perso/STB-Proxy/app.py", line 761, in channel
    if channels:
UnboundLocalError: local variable 'channels' referenced before assignment
```

**Comment by Chris230291** [comment]
Do you know of any servers that let you watch more than one stream?
Most servers break the old stream 30-60 seconds after you make a new stream. Some servers do this very quickly.

**Comment by CyberPoison** [comment]
magnum ott allow you multiple streams from one mac 😉

**Comment by Chris230291** [comment]
Added option to set streams per MAC
